# Generated by lynx_factory — the make + ./run contract for lynx-portfolio.
#
#   make          install dependencies (idempotent — safe on every clone)
#   make run      start the project with its defaults (same as ./run)
#   make check    verify the toolchain this project needs is present

.DEFAULT_GOAL := all
.PHONY: all deps run check

all: deps

deps:  # create .venv and install the package + its dependencies
	@RUN_MODE=deps ./run

run: deps
	@./run

check:
	@RUN_MODE=check ./run
